image: docker:19.03.0

variables:
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.0-dind

before_script:
  - apk update
  - apk add python3

build:
  stage: test
  script:
    - lscpu
    - cat /proc/cpuinfo
    - free -h
    - python3 benchtool_runner/main.py config_sample.json