arch:
  - amd64
  - arm64-graviton2

virt: vm

os: linux
dist: focal

language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
    
script:
  - lscpu
  - cat /proc/cpuinfo
  - python benchtool_runner/main.py config_sample.json 
    