sudo: required

language: python
python:
  - "3.8"

install:
  - sudo apt update
  - sudo apt install file
  - pip install -r requirements.txt

arch:
  - amd64
  - arm64

os: linux

matrix:
  include:
  - os: linux
    arch: amd64
  - os: linux
    arch: arm64
    
script:
  - file /bin/bash
  - lscpu
  - free -h
  - python benchtool_runner/main.py config_sample.json 
    