arch:
  - amd64
  #- arm64

os: linux

dist: bionic

language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

services:
  - docker

matrix:
  include:
  #- os: linux
  #  arch: amd64
  - os: linux
    arch: arm64
    
script:
  - python benchtool_runner/main.py config_sample.json 
    