arch:
  - amd64
  - arm64-graviton2

os: linux

dist: bionic

language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - docker

matrix:
  include:
  - os: linux
    arch: amd64
  - os: linux
    arch: arm64-graviton2
    virt: vm
    
script:
  - cat /proc/cpuinfo
  - lscpu
  - python benchtool_runner/main.py config_sample.json 
    