os: linux
dist: bionic
virt: lxd

language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

matrix:
  include:
  - arch: amd64
    script:
      - cat /proc/cpuinfo
      - lscpu
      - python benchtool_runner/main.py config_sample.json 
  - arch: arm64-graviton2
    script:
      - cat /proc/cpuinfo
      - lscpu
      - python benchtool_runner/main.py config_sample.json 
    