image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python3 benchtool_runner/main.py config_sample.json
        services:
          - docker
