version: 2.1

jobs:
  amd64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    steps:
      - checkout
      - run: pyenv install --list
      - run: pyenv install 3.6.3
      - run: pyenv global 3.6.3
      - run: lscpu
      - run: cat /proc/cpuinfo
      - run: free -h
      - run: pip install -r requirements.txt
      - run: python benchtool_runner/main.py config_sample.json
  arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: pyenv install --list
      - run: pyenv install 3.6.3
      - run: pyenv global 3.6.3
      - run: lscpu
      - run: cat /proc/cpuinfo
      - run: free -h
      - run: pip install -r requirements.txt
      - run: python benchtool_runner/main.py config_sample.json

workflows:
  build:
    jobs:
      - arm64
      - amd64
