name: Python application

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    container: docker:24.0-dind
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Run
      env:
        GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        RUNNER_ENV: ${{ secrets.RUNNER_ENV }}
        SEND_TO_SHEET: ${{ secrets.SEND_TO_SHEET }}
      run: |
        apk update
        apk add python3
        apk add py3-pip
        apk add util-linux
        lscpu
        free -m
        pip install -r requirements.txt
        python3 benchtool_runner/main.py config_sample.json
