name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - uses: brunoshiroma/setup-julialang@v0.3.0-SNAPSHOT
      with:
        julialang-version: '1.2.0'
    - uses: actions/setup-java@v1
      with:
        java-version: '12'
    
    - name: Run
      run: |
        python benchtool_runner/main.py config_sample.json
