name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker:19.03.11-dind
    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: |
        apk update
        apk add python3
        apk add util-linux
        lscpu
        free -m
        pip install -r requirements.txt
        python3 benchtool_runner/main.py config_sample.json
