name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: |
        python benchtool_runner/main.py config_sample.json
